apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-deployer-role
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
