apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: argocd
subjects:
  - kind: User
    name: flyingspark
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
