apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-mysql-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  source:
    repoURL: https://github.com/brutecoderMk/agoraCD.git
    targetRevision: master
    path: /agoraCD
  project: default
  syncPolicy:
    automated:
      prune: true   # Set to true to automatically delete resources not defined in Git
      selfHeal: true   # Set to true to automatically reconcile any drifts
