apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  destination:
    namespace: phpns
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/brutecoderMk/agoraCD.git
    targetRevision: HEAD
    path: wp
  project: default
  syncPolicy:
    automated: {}
