apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-httpd-pod
  namespace: project1

spec:
  selector:
    matchLabels:
      app: httpd-web
      location: IN
      environment: Production
      tier: frontend
  replicas: 1
  template:
    metadata:
      name: httpd-pod
      namespace: project1
      labels:
        app: httpd-web
        location: IN
        environment: Production
        tier: frontend

    spec:
      containers:
      - name: httpd-web
        #image: pawanitzone/gke-image:35
        image: pawanitzone/hyt-http:15
        volumeMounts:
            - name: httpd-volume
              mountPath: /opt
      volumes:
        - name: httpd-volume
          persistentVolumeClaim:
            claimName: httpd-pvc
