apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql   # Changed from "mysql8"
spec:
  selector:
    matchLabels:
      app: mysql   # Changed from "mysql8"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql   # Changed from "mysql8"
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: .sweetpwd.
        - name: MYSQL_DATABASE
          value: my_db
        - name: MYSQL_USER
          value: db_user
        - name: MYSQL_PASSWORD
          value: .mypwd
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
          name: mysql
