apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: phpns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-container
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: argodb
