apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-mysql-app
spec:
  project: default
  source:
    repoURL: https://github.com/brutecoderMk/agoraCD.git
    path: path/to/manifests
    targetRevision: HEAD
    path: prod
  destination:
    namespace: fpm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
