apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  namespace: phpns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress-container
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-db-service  # This should match the MySQL service name
            - name: WORDPRESS_DB_USER
              value: root  # This might be a different user you created
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: WORDPRESS_DB_NAME
              value: wordpress_db  # This should match the database name you created
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app-service
  namespace: phpns
spec:
  selector:
    app: wordpress-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
