apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: phpns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
        - name: php-container
          image: futureops/argofpm:latest
          ports:
            - containerPort: 9000
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
